In [1]:
import numpy as np

# =================================================================
# PARTE 1: TEORÍA (Explicar la diferencia entre Lista y Array)
# =================================================================
print("--- 1. DIFERENCIA ENTRE LISTA Y ARRAY ---")
lista_a = [1, 2, 3]
lista_b = [4, 5, 6]
# Las listas en Python son colecciones que no permiten aritmética directa, solo se concatenan (se unen)
print("Suma de Listas de Python (Se concatenan):", lista_a + lista_b)

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
# Los arrays de NumPy permiten operaciones matemáticas directas elemento por elemento
print("Suma de Arrays de NumPy (Aritmética directa):", array_a + array_b)

--- 1. DIFERENCIA ENTRE LISTA Y ARRAY ---
Suma de Listas de Python (Se concatenan): [1, 2, 3, 4, 5, 6]
Suma de Arrays de NumPy (Aritmética directa): [5 7 9]


In [2]:
# =================================================================
# PARTE 2: CÓDIGO BASE DEL VIDEO (Creación de Arrays)
# =================================================================
print("\n--- 2. FUNCIONES DE CREACIÓN DE NUMPY ---")

# 1. np.array(): Generar matrices 1D y 2D
matriz_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("1. Matriz 2D creada con np.array:\n", matriz_2d)

# 2. np.zeros(): Crea matrices llenas de ceros (útil para inicializar contadores)
ceros = np.zeros((2, 4))
print("\n2. Matriz de ceros con np.zeros:\n", ceros)

# 3. np.ones(): Crea matrices llenas de unos (útil para multiplicadores base)
unos = np.ones(5)
print("\n3. Matriz de unos con np.ones:\n", unos)

# 4. np.arange(): Crea una secuencia de números (inicio, fin exclusivo, saltos)
rango = np.arange(0, 10, 2)
print("\n4. Secuencia con np.arange (0 al 8 de 2 en 2):", rango)

# 5. np.linspace(): Crea una cantidad específica de valores espaciados uniformemente
espaciado = np.linspace(0, 100, 5)
print("\n5. Espaciado con np.linspace (5 valores entre 0 y 100):", espaciado)


--- 2. FUNCIONES DE CREACIÓN DE NUMPY ---
1. Matriz 2D creada con np.array:
 [[1 2 3]
 [4 5 6]]

2. Matriz de ceros con np.zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3. Matriz de unos con np.ones:
 [1. 1. 1. 1. 1.]

4. Secuencia con np.arange (0 al 8 de 2 en 2): [0 2 4 6 8]

5. Espaciado con np.linspace (5 valores entre 0 y 100): [  0.  25.  50.  75. 100.]


In [3]:
print("\n--- 3. CASO DE USO REAL: Gestión de Ventas ---")

# Contexto: Abrimos una nueva tienda de tecnología.
# Usamos np.zeros para inicializar el stock en sistema de 3 productos en 4 sucursales distintas.
stock_inicial = np.zeros((3, 4))
print("Stock inicial vacío en sistema (3 productos, 4 sucursales):\n", stock_inicial)

# Usamos np.ones para asignar un bono base garantizado de $1000 a 5 vendedores
bono_vendedores = np.ones(5) * 1000
print("\nBonos base inicializados para 5 empleados:", bono_vendedores)

# Usamos np.arange para generar los identificadores de los días laborables de la semana (Lunes=1 a Viernes=5)
dias_laborables = np.arange(1, 6)
print("\nDías laborables generados:", dias_laborables)

# Usamos np.linspace para calcular 4 metas de ventas trimestrales que deben subir gradualmente a lo largo del año
# Empezando con meta de 10,000 llegando a 40,000 al final del año.
metas_trimestrales = np.linspace(10000, 40000, 4)
print("\nMetas de ventas calculadas por trimestre:", metas_trimestrales)


--- 3. CASO DE USO REAL: Gestión de Ventas ---
Stock inicial vacío en sistema (3 productos, 4 sucursales):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Bonos base inicializados para 5 empleados: [1000. 1000. 1000. 1000. 1000.]

Días laborables generados: [1 2 3 4 5]

Metas de ventas calculadas por trimestre: [10000. 20000. 30000. 40000.]
