# Misión Práctica Equipo 1: Tablero de Ajedrez 8x8 con NumPy y Slicing
En esta sección construimos un tablero de ajedrez (matriz 8x8 de 0s y 1s) utilizando la librería NumPy, inspeccionamos sus atributos principales y extraemos subsecciones mediante la técnica de slicing.


In [1]:
import numpy as np

#### 1. Creación del tablero 8x8 lleno de ceros

In [2]:
tablero = np.zeros((8, 8), dtype=int)

#### 2. Asignación del patrón de ajedrez (unos intercalados)



In [3]:
# Filas pares (0, 2, 4, 6), columnas impares (1, 3, 5, 7)
tablero[::2, 1::2] = 1

# Filas impares (1, 3, 5, 7), columnas pares (0, 2, 4, 6)
tablero[1::2, ::2] = 1

print("=== TABLERO DE AJEDREZ (8x8) ===")
print(tablero)


=== TABLERO DE AJEDREZ (8x8) ===
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 3. Inspección de Atributos del Array

In [4]:
print("\n=== ATRIBUTOS DEL TABLERO ===")
print("Forma (.shape):", tablero.shape)
print("Dimensiones (.ndim):", tablero.ndim)
print("Total de elementos (.size):", tablero.size)
print("Tipo de dato (.dtype):", tablero.dtype)


=== ATRIBUTOS DEL TABLERO ===
Forma (.shape): (8, 8)
Dimensiones (.ndim): 2
Total de elementos (.size): 64
Tipo de dato (.dtype): int64


###4. Extracción de Secciones Específicas usando Slicing

In [5]:
cuadrante_sup_izq = tablero[0:4, 0:4]   # Primeras 4 filas y 4 columnas
centro_tablero = tablero[2:6, 2:6]      # Submatriz central de 4x4
esquina_inf_der = tablero[6:8, 6:8]     # Submatriz de 2x2 en la esquina inferior

print("\n=== EXTRACCIÓN CON SLICING (SUBSECCIONES) ===")
print("1. Cuadrante Superior Izquierdo (4x4):\n", cuadrante_sup_izq)
print("\n2. Centro del Tablero (4x4):\n", centro_tablero)
print("\n3. Esquina Inferior Derecha (2x2):\n", esquina_inf_der)



=== EXTRACCIÓN CON SLICING (SUBSECCIONES) ===
1. Cuadrante Superior Izquierdo (4x4):
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

2. Centro del Tablero (4x4):
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

3. Esquina Inferior Derecha (2x2):
 [[0 1]
 [1 0]]
